# Numpy Basics

In [1]:
import numpy as np

*code below is the most basic thing numpy can do*

In [2]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


*checking numpy version*

In [3]:
print(np.__version__)

1.26.4


### Create a NumPy ndarray Object

In [4]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


*type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.*

### 0-D Arrays
*
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.*

In [5]:
arr0=np.array(34)
print (arr0)

34


## 1-D Arrays
#### 
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D arra.

These are the most common and basic arrays.

In [6]:
arr1=np.array((1,2,3,4,5,6,7,8,9,10))
print (arr1)

[ 1  2  3  4  5  6  7  8  9 10]


*similarly the format is same for 2D and 3D arrays too*

In [7]:
arr2=np.array([[1,2,3],[4,5,6]])
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print('this is a 2D array')
print (arr2)
print('this is a 3D array')
print (arr3)

this is a 2D array
[[1 2 3]
 [4 5 6]]
this is a 3D array
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Check number of divisions

*NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.*

In [8]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d.ndim)

3


## Negative Indexing

*Use negative indexing to access an array from the end.*

arrlast = np.array([[1,2,3,4,5], [6,7,8,9,12]])
print('Last element from 2nd dim: ', arrlast[1, -1])

## Creating Arrays With a Defined Data Type

*We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:*

In [12]:
arrdp=np.array([1,2,3,4,5,6],dtype='S4')
print(arrdp.dtype)

|S4


## Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a paramete.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for inteer.*

In [17]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


## Reshaping arrays

*reshaping 1D array to 2D array*

In [19]:
resh=np.array([1,2,3,4,5,6,7,8,9])
newresh=resh.reshape(3,3)
print (newresh)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
resh=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36])
newresh=resh.reshape(3,2,6)
print (newresh)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]]


## Flattening the array

*converting multidimensional arrays into 1D array*

In [34]:
nnewresh=newresh.reshape(-1)
print (nnewresh)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


## Concatenating Arrays

In [37]:
carray=np.concatenate((arr,resh))
print (carray)

[ 1.1  2.1  3.1  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.
 12.  13.  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.
 26.  27.  28.  29.  30.  31.  32.  33.  34.  35.  36. ]


## Array Stacking

In [55]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.stack((a,b),axis=1) #STACK AROUND ROWS
d=np.hstack((a,b)) #HORIZONTAL STACK
e=np.vstack((a,b))#STACK AROUND COLUMNS
f=np.dstack((a,b))
print (c)
print (d)
print (e)
print (f)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


## Array Splitting

*We can split the arrays using array_split() functions*

In [57]:
splitresh=np.array_split(resh,4)
print (splitresh)

[array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18]), array([19, 20, 21, 22, 23, 24, 25, 26, 27]), array([28, 29, 30, 31, 32, 33, 34, 35, 36])]


*You can call each of the splited arrays accordingly*

In [60]:
print (splitresh[0])
print (splitresh[1])
print (splitresh[2])
print (splitresh[3])

[1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18]
[19 20 21 22 23 24 25 26 27]
[28 29 30 31 32 33 34 35 36]


## Searching Arrays

*where() method helps us find shit*

In [73]:
import numpy as np
prj = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(prj%2 == 1)
print('indexes where odd numbers are: ',x)
y=np.where(prj%2==0)
print('indexes where Even numbers are: ',y)

indexes where odd numbers are:  (array([0, 2, 4, 6], dtype=int64),)
indexes where Even numbers are:  (array([1, 3, 5, 7], dtype=int64),)


*There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.*

*The searchsorted() method is assumed to be used on sorted arrays.*

In [86]:
z=np.searchsorted(resh,6)
k=np.searchsorted(resh,9,side='right')
print('the index value where number 6 is stored is: ',z)
print('the index value where number 6 is stored from the right is: ',k)
print(resh)

the index value where number 6 is stored is:  5
the index value where number 6 is stored from the right is:  9
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


## Sorting Arrays

*The NumPy ndarray object has a function called sort(), that will sort a specified array.*

In [97]:
a=np.array([12,34,67,32,87,34,38,97,24,93,4,689,69,3,2,43,87])
b=np.sort(a)
c=np.array(['b','o','k','a'])
print (b)
print (np.sort(c))

[  2   3   4  12  24  32  34  34  38  43  67  69  87  87  93  97 689]
['a' 'b' 'k' 'o']


## Random

In [98]:
from numpy import random